# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

updateBranch: true
deleteBranchAfterMerge: true
reportStatus: true

minApprovals:
  COLLABORATOR: 0
maxRequestedChanges:
  NONE: 0
blockingLabels:
  - dont-merge

# Will merge whenever the above conditions are met, but also
# the owner has approved or merge label was added.
rules:
  - requiredLabels:
      - auto-merge

mergeCommitMessage: |
  {title} (#{number})
  {body}
mergeMethod: squash
