version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
    day: "monday"
    time: "00:00"
    timezone: "UTC"
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 99
