pull_request_rules:
  - name: Resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request has conflicts when rebasing. Could you fix it @{{author}}? 🙏
  - name: Automatic merge on approval
    conditions:
      - label=auto-merge
      - label=!dont-merge
    actions:
      merge:
        method: squash