name: Auto-gen
on:
  push:
    branches:
      - main
    paths:
      - 'IRIP/img/*/*'
      - 'auto-gen.py'
  pull_request:
    branches:
      - main
    paths:
      - 'IRIP/img/*/*'
      - 'auto-gen.py'


jobs:

  add-actions:
    name: gen-readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - run: git config --global user.name "readme-gen"
      - run: git config --global user.email "<>"
      - run: python auto-gen.py
      - run: git add README.md
      - run: git commit -m "auto generate README.md" || echo "nothing to commit, working tree clean"; exit 0
      - run: git push
